
version: "3"

services:
    nextjs:
        container_name: oysibot-twitch
        image: node
        restart: always
        ports:
            - "127.0.0.1:3000:3000"
        volumes:
            - ./:/app/
        command: bash -c 'cd /app/ && npm install && npm run build && npm run start'
